services:

  chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    container_name: chrome
    ports:
      - 4444:4444

  ftp-server:
    container_name: my-ftp-server
    user: root
    environment:
      - FTP_PASS=123
      - FTP_USER=user
    image: garethflowers/ftp-server
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp' # Only needed for passive mode
    volumes:
      - 'data:/home/user'

  ifirma_docs:
    profiles:
      - all
    container_name: ifirma_doc
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'data:/data'
    env_file:
      - ./env/.env.test
    ports:
      - "8080:80"
    
volumes:
  data: