services:

  chrome:
    image: selenium/standalone-chrome
    shm_size: 2gb
    container_name: ${APP}-${STAGE}-chrome

  ftp-server:
    container_name: ${APP}-${STAGE}-ftp-server
    user: root
    environment:
      - FTP_PASS=123
      - FTP_USER=user
    image: garethflowers/ftp-server
    ports:
      - '${FTP_PORTS}:20-21/tcp'
      - '${FTP_PASSIVE_PORTS}:40000-40009/tcp' # Only needed for passive mode
    volumes:
      - './data:/home/user'

  app:
    profiles:
      - all
    container_name: ${APP}-${STAGE}-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './data:/data'
    env_file:
      - ./env/.env.${STAGE}
    ports:
      - "${APP_PORT}:8080"
    healthcheck:
      test: ["CMD", "/app/healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    restart: always
volumes:
  data: